### ISSUE TITLE
Remove duplicates from IPMI SEL metric

### ISSUE THREAD

**Issue by sudeephb** [canonical/prometheus-hardware-exporter#25]
The IPMI SEL output looks something like this:
ID   | Date        | Time     | Name                                   | Type                     | State    | Event
----- | ------------ | ----------- | ------------------------------------ | ----------------------- | --------- | --------------------------------
493  | Oct-06-2022 | 19:47:13 | System Board ACPI_Stat                 | System ACPI Power State  | Nominal  | S0/G0
494  | Oct-06-2022 | 19:57:23 | System Chassis SysHealth_Stat          | Chassis                  | Critical | transition to Non-recoverable from less severe
496  | Oct-06-2022 | 19:57:51 | System Board ACPI_Stat                 | System ACPI Power State  | Nominal  | S0/G0
497  | Oct-06-2022 | 20:04:35 | System Board ACPI_Stat                 | System ACPI Power State  | Nominal  | S0/G0

In the metric [`ipmi_sel_state`](https://github.com/canonical/prometheus-hardware-exporter/blob/baeba367ce24a4ce7b57206f9a5d2657d732eafe/prometheus_hardware_exporter/collector.py#L518), we  use only the `Name`, `Type` and `State` fields (`State` is mapped to the value of the metric).
In the above set of logs, events `496` and `497` have exactly the same information except for `Time`, so the `ipmi_sel_state` metrics will look exactly the same. This happens very often and there will be lots of metrics with exactly the same labels and value.

In this kind of scenario, we should remove the duplicates and add only one metric to the registry with this set of labels and value.
Another solution might to include all the fields above in the metric labels.

**Comment by jneo8** [comment]
I suggest to take only the latest log as the output metrics.
The metrics should only shows the latest status, not history.

**Comment by jneo8** [comment]
Close #28
