### ISSUE TITLE
Flush cache while running ipmi commands

### ISSUE THREAD

**Issue by sudeephb** [canonical/prometheus-hardware-exporter#40]
Sometimes the outdated cache may cause error and cause the service to stop. We need to flush the cache when the service starts.
The cache may be helpful to make the collector faster, so we can discuss further on where to and where not to flush the cache.

IPMI provides a `-f` command to flush cache while running commands.

**Comment by pengwyn** [comment]
We are encountering this on a customer at the moment. For whatever reason, the cache is out of date within 10 minutes of flushing the cache, so applying the flush at the start of the service would not be sufficient.

I found that an alternative to `-f` exists: `--sdr-cache-recreate`. This will recreate the cache only if necessary when the `ipmi-sel` or `ipmimontoring` commands are run.

I added `--sdr-cache-recreate` to [this line](https://github.com/canonical/prometheus-hardware-exporter/blob/a3e06c5320c327cb1df33c2f436045cb18f140f9/prometheus_hardware_exporter/collectors/ipmi_sel.py#L26) and found that it worked for our customer.
