### ISSUE TITLE
ssacli collector selects the wrong slot

### ISSUE THREAD

**Issue by peppepetra** [canonical/prometheus-hardware-exporter#41]
I have the following HPE Smart Array RAID controller:

```
# ssacli ctrl all show

HPE Smart Array E208i-a SR Gen10 in Slot 12  (sn: PWDRD0ERHE11FB)
```

Collector splits that output by space and takes it as slot [0]

That returns slot = Gen10 instead of Slot 12.

Because of that it is not able to collect ssacli info correctly.

Relevant log:
```
Oct 26 12:42:02 machine3 python3[13131]: 2023-10-26 12:42:02 DEBUG Running command: ssacli ctrl slot=Gen10 show status
Oct 26 12:42:03 machine3 python3[13131]: 2023-10-26 12:42:03 ERROR Command 'ssacli ctrl slot=Gen10 show status' returned non-zero exit status 1.
Oct 26 12:42:03 machine3 python3[13131]: 2023-10-26 12:42:03 ERROR Command 'ssacli ctrl slot=Gen10 show status' returned non-zero exit status 1
```

0. https://github.com/canonical/prometheus-hardware-exporter/blob/main/prometheus_hardware_exporter/collectors/ssacli.py#L59

**Comment by peppepetra** [comment]
Changing that line to 
```
 slots.append(controller.split()[8])
```

it is enough to make it working, but we should make the slot extraction more robust.

**Comment by jneo8** [comment]
Ok, so because the parsing rule is split base on space and it doesn't support all the HP device models. We can simple fix it with different parse rule to make sure we get the right slot number.

Thanks @peppepetra , the information is really helpful.
