### ISSUE TITLE
Redfish collector try to login and logout on each scrape

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/prometheus-hardware-exporter#48]
The current implementation of redfish collector is not efficient because it tries to login and logout on [each scrape](https://github.com/canonical/prometheus-hardware-exporter/blob/066504132062908aee2b961a491275d8d4b9b329/prometheus_hardware_exporter/collector.py#L999). Ideally, after login, we can reuse the session for subsequent calls of `fetch`, and if the session is expired, then we can re-login again.

**Comment by gabrielcocenza** [comment]
@chanchiwai-ray  Is there any metrics showing how inefficient it is and what would be the gain?

**Comment by chanchiwai-ray** [comment]
No, I don't have the hardware to collect any metrics. From the code, it creates a connection and login and logout for each `fetch`, and that logically is not ideal, but I doubt that it has strong impact to the performance.

**Comment by aieri** [comment]
I would then close this for now. We can reopen if it seems to be a significant performance issue. Reusing the connection would add a little bit of extra complexity.
