### ISSUE TITLE
Handle different storage controller responses

### ISSUE THREAD

**Issue by sdemircan** [canonical/prometheus-hardware-exporter#57]
While checking storage controller data in `get_storage_controller_data` function API response varies between different ILO versions and different vendors(ie. Inspur).

**Comment by Pjack** [comment]
Could you share additional details or specifications about the requirements? This will help us understand how best to assist you.

**Comment by Pjack** [comment]
Since #71 is been merged. The scope should cover this one. Welcome to reopen it or submit new PR if we miss anything. thanks
