### ISSUE TITLE
Handle long queries

### ISSUE THREAD

**Issue by sudeephb** [canonical/prometheus-hardware-exporter#66]
Some metrics take too much time to be fetched(eg. `ipmi-sel` as reported on #62 ). We need to find a robust solution to handle this kind of issues. The solution may(or may not) involve 
- increasing the prometheus scrape interval and timeout, 
- implementing cache for long-running queries
- Running background checks to fetch metrics independently and write to a file/db, from where grafana-agent can read.

Note that the default prometheus scrape interval is 1m and scrape timeout is 10s.

**Comment by Pjack** [comment]
Partly solved in 
https://github.com/canonical/hardware-observer-operator/issues/282 
https://github.com/canonical/hardware-observer-operator/pull/193

With the recent enhancements, I’d like to close this ticket for now unless a specific issue arises again. 
It's difficult to track the issue without a well-defined problem statement.
